# Generated by Django 6.0.3 on 2026-03-06 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('registration_number', models.CharField(help_text='Format e.g. 231-D-12345', max_length=20, primary_key=True, serialize=False)),
                ('front_image', models.ImageField(upload_to='vehicles/front_images/')),
                ('vehicle_type', models.CharField(choices=[('Two-Wheeler', 'Two-Wheeler'), ('Four-Wheeler', 'Four-Wheeler')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('kilometres_travelled', models.PositiveIntegerField()),
                ('seller_expected_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('house_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('C', 'Cork'), ('CE', 'Clare'), ('CN', 'Cavan'), ('CW', 'Carlow'), ('D', 'Dublin'), ('DL', 'Donegal'), ('G', 'Galway'), ('KE', 'Kildare'), ('KK', 'Kilkenny'), ('KY', 'Kerry'), ('L', 'Limerick'), ('LD', 'Longford'), ('LH', 'Louth'), ('LM', 'Leitrim'), ('LS', 'Laois'), ('MH', 'Meath'), ('MN', 'Monaghan'), ('MO', 'Mayo'), ('OY', 'Offaly'), ('RN', 'Roscommon'), ('SO', 'Sligo'), ('T', 'Tipperary'), ('W', 'Waterford'), ('WH', 'Westmeath'), ('WX', 'Wexford'), ('WW', 'Wicklow')], max_length=2)),
                ('eircode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Valuation Completed', 'Valuation Completed'), ('Listed', 'Listed'), ('Interest Received', 'Interest Received'), ('Buyer Selected', 'Buyer Selected'), ('Deal Accepted', 'Deal Accepted'), ('Transferred', 'Transferred'), ('Ownership Pending', 'Ownership Pending'), ('Ownership Completed', 'Ownership Completed')], default='Submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_road_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('assumed_depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_months_used', models.IntegerField(blank=True, null=True)),
                ('total_depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rounded_residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_system_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='vehicles.vehicle')),
            ],
        ),
    ]
